output_path:
output_name: # stem

input_img_path: ../path/to/raster/file.tif
channels: [1, 2, 3, 4, 5]

truth_path : ../path/to/truth/file.tif
metrics_out: ../path/to/metrics/file.csv # None = new file

img_pixels_detection: 512
margin: 128
output_type: "argmax"
n_classes: 19


model_weights: ../path/to/model/weights.pth  #e.g., FLAIR-INC_rgbie_15cl_resnet34-unet_weights.pth
model_framework: 
    model_provider: HuggingFace
    
    HuggingFace:
        org_model: openmmlab/upernet-swin-small
    SegmentationModelsPytorch:
        encoder_decoder: resnet34_unet


batch_size: 4
use_gpu: true
num_worker: 2

write_dataframe: False

norma_task: 
  - norm_type: custom 
    norm_means: [105.08, 110.87, 101.82, 106.38, 53.26]
    norm_stds: [52.17, 45.38, 44, 39.69, 79.3]

overlap_strat: 

strategies:
  tiling: 
    enabled : False
    size_range: []
    stride_range: []
  stitching:
    enabled : False
    method: ["average", "max", "exact_clipping"]
    margin: []
  padding_overall: ~ # mirror, zero...

