compile: false
prune: false # use pruna.ai optimization methods
quantize: true

prune_args:
  precision: float32 # int8
  flag: pruna
  sparse: 0.005
  methods:
    pruner: torch_unstructured
    quantizer: half

available_quantize_methods: [pytorch, quanto, torchao ] # let's not handle onnx optimization for now
quantize_method: quanto # default method

pytorch_args: # method name and args name have to match exactly !!
  flag: pytorch
  precision : float32
  available_methods: [dynamic]

quanto_args:
  flag: quanto
  precision: int8
  method: weight_only # dynamic # or static or weight_only
  calibration_dataset: ./0testing_saves/calibration_dataset
  methods:
    dynamic :
      calibration: False
      weights: qint8
      activations: qint8
    static :
      calibration: True
      weights: qint8
      activations: qint8
    weight_only :
      calibration: False
      weights: qint8
      activations: None
  incompatible : ['compile']
