pytorch_baseline :
  enable : true
  precision : float32

onnx_baseline :
  enable : true
  precision : float32
  flag : onnx

pruned : 
  enable : true
  precision : float32 
  flag : pruna
  sparse : 0.005
  methods:
    pruner : torch_unstructured

pruna_half :
  enable : true
  precision : float16
  flag : pruna
  methods:
    quantizer : half

pruna_half_pruned :
  enable : true
  precision : float16
  flag : pruna
  sparse : 0.005
  methods:
    pruner : torch_unstructured
    quantizer : half

pytorch_bf16 : 
  enable : true
  precision : bfloat16
  flag: pytorch

ao_weights-only_int8 :
  enable : true
  precision : int8
  flag : torchao